version: '3'

services:
  server:
    image: nginx:alpine
    container_name: ${APP_NAME}_SERVER
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/ssl:/etc/ssl
      - ./app:/var/www/html/public
      - ./config/nginx/default.template.conf:/etc/nginx/conf.d/default.template
    ports:
      - ${APP_SERVER_PORT}:80
      - ${APP_SERVER_PORT_SSL}:443
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - db

  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    container_name: ${APP_NAME}_PHP
    restart: always
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./app:/var/www/html/public

  composer:
    image: composer
    container_name: ${APP_NAME}_COMPOSER
    volumes:
      - ./app:/app
    command: install

  db_admin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_MY_SQL_ADMIN
    ports:
      - ${APP_ADMIN_DB}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
    restart: always
    depends_on:
      - db

  db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${APP_NAME}_DB
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${APP_DB_PORT}:3306
    volumes:
      - ./data/db:/var/lib/mysql